Layout/AlignParameters:
  Enabled:  false

Layout/CaseIndentation:
  Enabled:  false

Layout/EmptyLinesAroundBlockBody:
  Enabled:  false

Layout/EmptyLinesAroundClassBody:
  Enabled:  false

Layout/EmptyLinesAroundModuleBody:
  Enabled:  false

Layout/EndAlignment:
  EnforcedStyleAlignWith:  start_of_line

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundOperators:
  Enabled:  false

Layout/TrailingBlankLines:
  Enabled:  false

Metrics/BlockLength:
  ExcludedMethods: [ RSpec.describe ]

Metrics/MethodLength:
  Enabled:  true
  Max: 25

Style/IfUnlessModifier:
  Enabled:  false

