Layout/AlignParameters:
  Enabled:  false

Layout/CaseIndentation:
  Enabled:  false

Layout/EmptyLinesAroundBlockBody:
  Enabled:  false

Layout/EmptyLinesAroundClassBody:
  Enabled:  false

Layout/EmptyLinesAroundModuleBody:
  Enabled:  false

Layout/EndAlignment:
  EnforcedStyleAlignWith:  start_of_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  Enabled:  false
  EnforcedStyle: indented
  IndentationWidth: 2

Layout/SpaceAroundOperators:
  Enabled:  false

Layout/TrailingBlankLines:
  Enabled:  false

Metrics/AbcSize:
  Max: 15

Metrics/BlockLength:
  Max: 30
  ExcludedMethods: [ RSpec.describe, Specification.new]

Metrics/MethodLength:
  Enabled:  true
  Max: 25

Style/IfUnlessModifier:
  Enabled:  false

Style/EmptyElse:
  EnforcedStyle: empty
